pipeline:
  name: Sample
  identifier: Sample
  projectIdentifier: Demo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build and Test
        identifier: Build_and_Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Test
                  identifier: Test
                  spec:
                    connectorRef: Docker_Registry
                    image: node
                    shell: Sh
                    command: npm test
                    privileged: false
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Docker_Registry
                    repo: docsbydeepak/node-app
                    tags:
                      - latest
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: HelloWorld
          environment:
            environmentRef: dev_1689847654378
            deployToAll: false
            infrastructureDefinitions:
              - identifier: devcluster_1689847654378
          execution:
            steps:
              - step:
                  type: K8sApply
                  name: K8sApply_1
                  identifier: K8sApply_1
                  spec:
                    filePaths:
                      - deployment
                    skipDryRun: false
                    skipSteadyStateCheck: false
                    skipRendering: false
                    overrides:
                      - manifest:
                          identifier: deployment
                          type: Values
                          spec:
                            store:
                              type: Github
                              spec:
                                connectorRef: account.Github_OAuth_1689838783895
                                gitFetchType: Branch
                                paths:
                                  - deployment
                                repoName: https://github.com/deepz-here/harness-ci-example
                                branch: main
                  timeout: 10m
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  delegateSelectors:
    - docker-delegate
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1689838783895
        repoName: deepz-here/harness-ci-example
        build: <+input>
